# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CatalystX-CRUD-Controller-RHTMLO
version:      0.15
version_from: lib/CatalystX/CRUD/Controller/RHTMLO.pm
installdirs:  site
requires:
    CatalystX::CRUD:               0.28
    Rose::HTML::Objects:           0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
